# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Architecture
    pod 'ReactorKit'
    
    # Networking
    pod 'Alamofire'
    pod 'Moya'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'SwiftyJSON'
    pod 'BSText'
    pod 'ReachabilitySwift'
    
    
    # UI
    pod 'SnapKit'
    pod 'TYCyclePagerView'
#    pod 'TYPagerController'
    pod 'MJRefresh'
    pod 'JXBanner'
    pod 'JXSegmentedView'
    #tabbar样式
    pod 'ESTabBarController-swift'
    #导航
    pod  'GKNavigationBarSwift'
    pod  'MBProgressHUD'
    pod  'FMDB'
    pod 'CalendarPicker'
    pod 'SwiftPopup'
    pod 'LLSegmentViewController'
    
    #oc 
    pod 'Masonry'
    pod 'ZJKitTool'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
